version: '3'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app-backend
    ports:
      - '4000:4000'
    container_name: scores_backend
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=mydatabase
      - DB_HOST=db
      - NODE_ENV=development
    restart: always
    depends_on:
      - db
  db:
    image: timescale/timescaledb:latest-pg14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    restart: always